name: build
on: [push, pull_request]

jobs:
  lab1:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build solution
        run: msbuild lab1\ImGui-Simple.sln
